### ISSUE TITLE
fbitdump filtering on da6/dstip6 gives empty result set

### ISSUE THREAD

**Issue by DRiKE** [CESNET/ipfixcol#104]
Selecting an IPv6 address that is definitely in the data, via

    fbitdump -R path/to/fbit_flows -o long6 -c10

and using that to filter the data on, like

    fbitdump -R path/to/fbit_flows '%dstip6 == 2001:db8:1911:b111::148:14:0'

does not yield any results, while they are expected. There is no difference in using da6, dstip6, =, ==.
If needed, I can provde the dataset for this.

**Comment by thorgrin** [comment]
This might be related to a known bug in FastBit library. Could you send me that data set to thorgrin |at| cesnet.cz? It works fine on my data.

**Comment by thorgrin** [comment]
I've tracked it down to a FastBit issue. You can watch the progress here: https://hpcrdm.lbl.gov/pipermail/fastbit-users/2015-July/002107.html
After the FastBit guys fix this, I'll update out clone of the FastBit library and close the issue.

**Comment by DRiKE** [comment]
Thanks a lot, I'll keep an eye on that.

**Comment by thorgrin** [comment]
I've just got an answer from the FastBit developers. We need to say that the filtered numbers are long and unsigned. I've just push an update to devel branch that should fix it for default types such as mac addresses and IPv6. The filter now also allows to add UL to any number so that the FastBit will treat it as unsigned long instead of double.
