### ISSUE TITLE
fastbit issues when compiling ipfixcol

### ISSUE THREAD

**Issue by batcavelabs** [CESNET/ipfixcol#184]
I get the following error when trying to compile ipfixcol:

checking for library containing fastbit_init... -lfastbit
./configure: line 16768: syntax error near unexpected token `LIBFASTBIT,'
./configure: line 16768:`PKG_CHECK_MODULES(LIBFASTBIT, fastbit >= 2.0.3.2,,'
configure: error: ./configure failed for tools/fbitdump

I've install fastbit and pkg_config is installed:

`# fastbit-config  --version
FastBit 2.0.3.2
`

`# pkg-config --version
0.28
`

This is on ubuntu 16.04

**Comment by thorgrin** [comment]
Can you please post config.log and the generated configure script itself?

**Comment by jnathan** [comment]
Perhaps I can add more clarity to this issue.  Having built and installed fastbit from the ipfix clone repository specified in the README.md, the autoconf generated configure for ipfixcol fails in tools/fbitdump if the user doesn't install libfastbit _correctly_.

checking for LIBFASTBIT... no
configure: error: Fastbit library version is too low (< 2.0.3.2)
configure: error: ./configure failed for tools/fbitdump
ubuntu@ubuntu-xenial:~/src/ipfixcol$ fastbit-config --version
FastBit 2.0.3.2

The problem comes in _not_ running autoreconf -i **before** running ./configure, make, and make install when building the cloned libfastbit.

If one fails to run autoreconf -i, fastbit.pc is neither generated nor installed and this can't be found with pkg-config.

It might be worth it to better highlight the build instructions or to tweak the autoconf/automake configuration to better ensure all the files are generated each and every invocation.

**Comment by thorgrin** [comment]
Thanks for the explanation. I've updated the README for libfastbit to say that the autoreconf is really necessary. It does not show my intended highlight, but I hope it will help anyway.
