### ISSUE TITLE
Logging?

### ISSUE THREAD

**Issue by alexwbai** [CESNET/ipfixcol#207]
Hi,

What is the recommended way to diagnose issues with ipfixcol?  We have a pipeline that takes in UDP ipfix data and converts it to TCP.  We are seeing missing records and I'd like to pinpoint where in the pipeline we are losing records.  Does ipfixcol have any logging capabilities or log files I can tail to take a look for errors or anything?

Thanks!
AlexW

**Comment by thorgrin** [comment]
Hello,

it depends on how much data you have. 
1) You can use verbose output to see processing of every packet, but that is useful only for small samples.
2) You can use statistics (-S switch) to look at how much data are passing through the collector and how much data is lost (based on sequence numbers)
3) I like to use nstat tool to look at number of dropped UDP packets (first see whether it is constant before sending the IPFIX packets to exclude bias from other processes). This can help diagnose packets that are lost before reaching IPFIXcol.

**Comment by alexwbai** [comment]
thanks thorgrin...  quick question:
While the ipfixcol was running (without issues) I had changed the system time from Eastern Time to UTC time.  Do you foresee that would affect ipfixcol in any way?

**Comment by thorgrin** [comment]
Did you just change the timezone or ajdust the time as well? The timezone should not really matter to the IPFIXcol core, however, there may be some problems with fastbit storage plugin (which you probably do not use anyway).

If you changed time, you can expect some inconsistencies (due to template timeouts), but everything should eventually correct itself in a short time.
