### ISSUE TITLE
IPFIX Header Observation ID decoding and send to JSON format to next node

### ISSUE THREAD

**Issue by shiv1997narayan** [CESNET/ipfixcol#211]
IPFIX Header Observation ID decoding and send to JSON format to next node

How IPFIX col decode Observation ID from IPFIX header and same to decoded in JSON format to send next node in each flow.

One IPFIX message have multiple Flows.

**Comment by Lukas955** [comment]
Hello,

the JSON plugin goes through the whole IPFIX message and independently converts each Data Record to JSON object. Since we have already developed the second generation of the IPFIXcol, which is available [here](https://github.com/CESNET/ipfixcol2/), consider using it instead of this first generation - it is 2x faster and much safer. 

I assume that you probably want to have Observation Domain ID as a part of the converted record. It is possible with the last modifications added in `devel` branch of the new collector with enabled option `<detailedInfo>`. The `devel` branch is quite stable now as we would like to make a new package soon. 

Best regards
Lukas
